

name: Runme

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["900 905 1", "900 905 2", "900 905 3", "900 905 4", "905 910 5", "905 910 6", "905 910 7", "905 910 8", "910 915 9", "910 915 10", "910 915 11", "910 915 12", "915 920 13", "915 920 14", "915 920 15", "915 920 16", "920 925 17", "920 925 18", "920 925 19", "920 925 20"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v4
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          node-version: 18
      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          RANGE_INDEX: ${{ matrix.rangeIndex }}
          MY_DATA: ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        with:
          args: |
            npm run start
      - name: done
        run: exit
