

name: Runme

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["1050 1055 1", "1050 1055 2", "1050 1055 3", "1050 1055 4", "1055 1060 5", "1055 1060 6", "1055 1060 7", "1055 1060 8", "1060 1065 9", "1060 1065 10", "1060 1065 11", "1060 1065 12", "1065 1070 13", "1065 1070 14", "1065 1070 15", "1065 1070 16", "1070 1075 17", "1070 1075 18", "1070 1075 19", "1070 1075 20"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v4
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          node-version: 18
      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          RANGE_INDEX: ${{ matrix.rangeIndex }}
          MY_DATA: ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        with:
          args: |
            npm run start
      - name: done
        run: exit
