

name: Runme

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["1100 1105 1", "1100 1105 2", "1100 1105 3", "1100 1105 4", "1105 1110 5", "1105 1110 6", "1105 1110 7", "1105 1110 8", "1110 1115 9", "1110 1115 10", "1110 1115 11", "1110 1115 12", "1115 1120 13", "1115 1120 14", "1115 1120 15", "1115 1120 16", "1120 1125 17", "1120 1125 18", "1120 1125 19", "1120 1125 20"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v4
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          node-version: 18
      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          RANGE_INDEX: ${{ matrix.rangeIndex }}
          MY_DATA: ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        with:
          args: |
            npm run start
      - name: done
        run: exit
