

name: Runme

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["1075 1080 1", "1075 1080 2", "1075 1080 3", "1075 1080 4", "1080 1085 5", "1080 1085 6", "1080 1085 7", "1080 1085 8", "1085 1090 9", "1085 1090 10", "1085 1090 11", "1085 1090 12", "1090 1095 13", "1090 1095 14", "1090 1095 15", "1090 1095 16", "1095 1100 17", "1095 1100 18", "1095 1100 19", "1095 1100 20"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v4
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          node-version: 18
      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          RANGE_INDEX: ${{ matrix.rangeIndex }}
          MY_DATA: ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        with:
          args: |
            npm run start
      - name: done
        run: exit
